apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::146549408816:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NCLD1GPDED08
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::146549408816:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-23T18:00:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1556"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6fe5108a-72f2-490c-bced-7dfea33e23ba
